name: Unity Build and Artifact Upload

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/setup-unity@v1
      with:
        unityVersion: 2021.1.x
        unityChannel: 'unity'
      
    - name: Build for Windows
      run: unity -quit -batchmode -projectPath ../../Chromatief -executeMethod BuildScript.BuildWindows -logFile build.log

    - name: Build for macOS
      run: unity -quit -batchmode -projectPath ../../Chromatief -executeMethod BuildScript.BuildMac -logFile build.log

    - name: Build for Linux
      run: unity -quit -batchmode -projectPath ../../Chromatief -executeMethod BuildScript.BuildLinux -logFile build.log

    - name: Archive and upload artifacts - Windows
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: Chromatief-${{ github.ref_name }}-Windows
        path: ./Chromatief/Builds/Windows

    - name: Archive and upload artifacts - macOS
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: Chromatief-${{ github.ref_name }}-macOS
        path: ./Chromatief/Builds/macOS

    - name: Archive and upload artifacts - Linux
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: Chromatief-${{ github.ref_name }}-Linux
        path: ./Chromatief/Builds/Linux
